# action.yml
name: Prepare
description: Prepares the repo for a typical CI job

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 9

    - uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Install dev dependencies
      shell: bash
      run: |
        pnpm add -D eslint-config-prettier -w
        pnpm add -D @eslint/eslintrc -w
        pnpm add -D eslint-import-resolver-typescript -w
        pnpm add -D eslint-plugin-import -w
        pnpm add -D knip -w
